# Generated by Django 6.0.4 on 2026-04-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('social_rank', models.FloatField(blank=True, null=True)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
